esphome:
  name: pump-controller

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

web_server:
  port: 80

# Enable Home Assistant API
api:
  password: "#15Sand1ker"

ota:
  - platform: esphome
    password: "#15Sand1ker"

wifi:
  ssid: "FAM_SAN_TRE"
  password: "XKV6hizv8nqUamfXxB6jJ9vW8yzmyR"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pump-Controller Fallback Hotspot"
    password: "bxwFVJtuGpsn"

captive_portal:

light:
  - platform: neopixelbus
    pin: GPIO8
    type: GRB
    variant: WS2812
    num_leds: 1
    name: "NeoPixel Light"
    id: neopixel_light

switch:
  - platform: gpio
    pin: GPIO4
    name: "Switch"
    on_turn_on:
      - light.turn_on:
          id: neopixel_light
          red: 0
          green: 100%
          blue: 100%
    on_turn_off:
      - light.turn_off:
          id: neopixel_light
